# Dependabot configuration file
# yaml-language-server: https://json.schemastore.org/dependabot-2.0.json
---
version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    groups:
      app:
        patterns:
          - "Microsoft.*"
          - "Spectre.*"
          - "System.*"
      tools:
        patterns:
          - "GitVersion.Tool"
